version: '3.9'

services:

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_project
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "5050:8080"  # Adminer sera accessible sur le port 5050 de l'hôte
    depends_on:
      - db

volumes:
  db_data:
